# Site settings
title: The Ngoding
email: congfandi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bukan yang paling bisa, sebatas ingin berbagi saja.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thengoding.com" # the base hostname & protocol for your site
twitter_username: congfandi
github_username:  congfandi

# Build settings
markdown: kramdown

paginate: 4

author: Cong Fandi

gems: [jekyll-paginate]

plugins:
  - jekyll-time-to-read